### ISSUE TITLE
使用CSS为所有无内容标签设置缺省文本

### ISSUE THREAD

**Issue by chansee97** [chansee97/my-blogs#36]
可以用这种纯css方式设置，此代码为示例，`*`选择器并不是很合适，需要换成自己的类名
```css
*:is(:empty) {
	position: relative;
	&::after {
		content: "没有内容";
		position: absolute;
		inset: 0;
		display: flex;
		justify-content: center;
		align-items: center;
	}
}
```
也可以设置为缺省图，使用`background-image`即可，方式大同小异
