### ISSUE TITLE
使用图片作为icon的css配置

### ISSUE THREAD

**Issue by chansee97** [chansee97/my-blogs#42]
设置一个元素作为图片
```html
<span class="ai-icon" />
```
具体css设置, 如果不想图片和文字颜色保持一致，则不需要设置mask

```css
.ai-icon{
  display: inline-block;
  width: 1lh;
  height: 1lh;
  background-color: currentColor;
  -webkit-mask: url(../../assets/img/ai-service.png) no-repeat;
  mask: url(../../assets/img/ai-service.png) no-repeat;
  -webkit-mask-size: 100% 100%;
  mask-size: 100% 100%;
}
```
