### ISSUE TITLE
YOLO环境配置

### ISSUE THREAD

**Issue by chansee97** [chansee97/my-blogs#49]
## miniconda 下载

[清华大学镜像站](https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/), 选择py38的版本[Miniconda3-py38_22.11.1-1-Windows-x86_64.exe](https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-py38_22.11.1-1-Windows-x86_64.exe)

## 创建环境
 
```sh
conda create -n yolov8 python=3.8
```
修改用户目录下的 .condarc 文件来使用 TUNA 镜像源
```
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  deepmodeling: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/
ssl_verify: false
```
切换到刚创建的环境
```sh
conda activate yolov8
```
配置PyPI 镜像
```sh
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
```

## 前置环境配置

查看本机CUDA版本, 我自己是11.7版本
```sh
nvidia-smi
```

安装`PyTorch`，具体安装看指令看[官网](https://pytorch.org/)，注意CUDA版本不要超过本机的
- 必须使用官网的命令进行安装，否则安装的是cpu的版本
- amd的独立显卡或者没有独立显卡的机器安装cpu版本即可
```sh
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2
```

下载[ultralytics](https://github.com/ultralytics/ultralytics/releases), 然后进入项目安装依赖
```sh
G:\project\ultralytics-8.2.30>conda activate yolov8

(yolov8) G:\project\ultralytics-8.2.30>

pip install -e .
```

验证是否安装成功
```sh
yolo

 Arguments received: ['yolo']. Ultralytics 'yolo' commands use the following syntax:
// ...
```
安装便利性的工具
```sh
pip install jupyterlab tensorboard
```
